boolean:
  ENABLE_DB_UPSERT_MODE: false
  ENABLE_UPLOAD_DUPLICATED_FILE: true
  ENABLE_DB_LOG: false
number:
  SET_ENABLE_PARSE_WITH_HEADER: 300
  SET_MAX_CONSOLE_ITEMS: 300
  SET_MAX_UPLOAD_HISTORY: 100
  SET_PARSE_FILE_RETURN_FREQ: 1000
