boolean:
  ENABLE_DATABASE: true
  ENABLE_DB_UPSERT_MODE: false
  ENABLE_PARSE_WITH_HEADER: true
number:
  SET_ENABLE_PARSE_WITH_HEADER: 300
  SET_MAX_CONSOLE_ITEMS: 300
  SET_MAX_UPLOAD_HISTORY: 100
  SET_PARSE_FILE_RETURN_FREQ: 1000
string:
  MsgParseFileFinished: 文件读取完成！
  MsgSaveDbFinished: 数据库存储完成！
  MsgParseHeaderError: |-
    由于文件格式不规范导致无法解析，请在wps/excel中另存为.csv格式，然后尝试重新上传。
    如果仍无法解决，请反馈！
  MsgDatabaseNotEnabled: Database not enabled
